name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
permissions:
  contents: read
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./

    - name: Deployment
      run: |
        python app.py 


    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
